/**
 * The catalog rendered as markdown.
 *
 * Two consumers, one module. `scripts/build-skill.ts` writes the reference the
 * agent skill ships, and `apps/web` serves a rule over HTTP so an agent that
 * can only fetch a URL gets the same answer the CLI gives. Neither could
 * import the other, and a second renderer would drift the first time a rule
 * changed shape.
 *
 * Pure, like format.ts. No filesystem, no clock: the file writing stays in
 * the script.
 */
import { baselineShortLabel, resolveBaseline } from "./baseline.ts";
import { GUIDE_SOURCE, guideCommand, resolveGuides } from "./guides.ts";
import { rules } from "./rules/index.ts";
import type { Rule } from "./schema.ts";

/** Where a rule is served as markdown. Interpolated into both renderers. */
const RULE_MARKDOWN_BASE = "https://youmightnotneed.dev/rules";

/** The markdown URL for one rule. */
export function ruleMarkdownUrl(id: string): string {
  return `${RULE_MARKDOWN_BASE}/${id}.md`;
}

/**
 * Codepoint order, not localeCompare: check-freshness byte-compares the
 * generated reference, and collation differs by locale and by ICU build. A
 * maintainer on lt_LT would otherwise regenerate a file that fails CI with no
 * data change.
 */
function byText(a: string, b: string): number {
  if (a < b) return -1;
  if (a > b) return 1;
  return 0;
}

/**
 * The index that makes the catalog useful before a dependency exists. Keyed by
 * `agent.when`, which is the use case rather than the package name, so an
 * agent about to build a carousel can find the rule without knowing that
 * swiper is the package it was reaching for.
 */
export function renderUseCaseTable(): string {
  const rows = [...rules]
    .sort((a, b) => byText(a.agent.when, b.agent.when))
    .map((rule) => {
      const status = baselineShortLabel(resolveBaseline(rule).status);
      return `| ${rule.agent.when} | ${rule.native} | ${status} | \`${rule.id}\` |`;
    });

  return [
    "| Building | The platform does | Support | Rule |",
    "| --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/**
 * One rule, in full. The `unless` conditions are the point of this: they are
 * what stops a finding from overstating itself, and until this existed they
 * were reachable only through the CLI's --verbose or the MCP server.
 */
export function renderRuleMarkdown(rule: Rule): string {
  const baseline = resolveBaseline(rule);
  const support = `${baselineShortLabel(baseline.status)}${
    baseline.limitedBy ? ` (capped by ${baseline.limitedBy.name})` : ""
  }`;

  return `# ${rule.title}

- **id**: \`${rule.id}\`
- **native**: ${rule.native}
- **support**: Baseline ${support}
- **replaces**: ${rule.replaces.map((pkg) => `\`${pkg}\``).join(", ")}

## When this applies

${rule.agent.when}.

A match is a starting point, not a verdict. A package in package.json is not
evidence of what it is used for, so read the conditions below before changing
anything.

## Keep the dependency if any of these apply

${rule.agent.unless.map((condition) => `- ${condition}`).join("\n")}

## The swap

\`\`\`
${rule.agent.snippet}
\`\`\`

## How to implement it

${renderGuides(rule)}
`;
}

/**
 * The hand-off from "which dependency can go" to "how to build the thing
 * properly". IDs and links only: the catalog is a lookup table, so nothing
 * here copies upstream prose. The attribution is what the licence asks for.
 */
function renderGuides(rule: Rule): string {
  const linkable = resolveGuides(rule).filter((guide) => guide.url !== null);
  const source = `Guides come from ${GUIDE_SOURCE.owner}'s ${GUIDE_SOURCE.name} (${GUIDE_SOURCE.licence}), ${GUIDE_SOURCE.repo}.`;

  if (linkable.length === 0) {
    return `No guide covers this rule yet. ${source}`;
  }

  const links = linkable
    .map((guide) => `- [${guide.id}](${guide.url}) (${guide.category})`)
    .join("\n");

  return `This catalog stops at the swap. These go through the implementation,
the fallbacks and the platform quirks.

${links}

Pull them into context with:

\`\`\`sh
${guideCommand(linkable.map((guide) => guide.id))}
\`\`\`

${source}`;
}

/**
 * The reference the agent skill loads on demand. Hybrid by design: the table
 * works offline and with no network, and the per-rule detail is fetched, so
 * the skill stops shipping a snapshot of prose that goes stale between
 * releases.
 */
export function renderCatalogReference(): string {
  const packageCount = new Set(rules.flatMap((rule) => rule.replaces)).size;

  return `<!-- Generated by scripts/build-skill.ts. Do not edit by hand. -->
<!-- Run \`pnpm refresh:skill\` to update. -->

# The catalog

Every rule, ${rules.length} of them, covering ${packageCount} npm packages.
Support is the Baseline tier of the least-supported feature the replacement
needs, so a rule reads as limited if any one part of it is.

## By use case

Read this before reaching for a package. The left column is the case the
native approach covers, so it is searchable without knowing which library you
were about to install.

${renderUseCaseTable()}

## Reading one rule

A row is a starting point, not a verdict. Every rule also carries the
conditions where the dependency is still right, the swap, and the guides that
cover the implementation. Those are not in this file. Take the rule id from
the table and fetch it:

\`\`\`sh
curl -sS ${ruleMarkdownUrl("<id>")}
\`\`\`

That is always the live catalog, where this table is only as fresh as the
version of the skill you have. Offline, or checking a package name rather
than a use case:

\`\`\`sh
npx -y youmightnotneed@latest --package <name> --verbose
\`\`\`
`;
}
