import { resolveFeature, rulesById } from "@youmightnotneed/catalog";
import type { Metadata } from "next";
import Link from "next/link";
import { BaselineBadge } from "@/components/baseline-badge";

export const metadata: Metadata = {
  title: "What this site uses",
  description:
    "This site is built from the same catalog it publishes. Here is which native feature does what, and where the fallback is.",
};

/**
 * A tool that tells you to drop libraries should be able to show its own work.
 * Each entry names a real feature used on this site, what it replaced, and
 * what happens in a browser that does not support it.
 */
interface Usage {
  featureId: string;
  where: string;
  instead: string;
  fallback: string;
  /** The catalog rule this exercises, when there is one. */
  ruleId?: string;
}

const USAGE: readonly Usage[] = [
  {
    featureId: "field-sizing",
    where: "The paste box on the home page grows as you type.",
    instead: "react-textarea-autosize, or a hidden mirror element to measure.",
    fallback: "A fixed-height textarea that scrolls.",
    ruleId: "field-sizing",
  },
  {
    featureId: "has",
    where:
      "The tier filter on the catalog page, and the hint under the submit button.",
    instead: "Component state and a re-render on every change.",
    fallback:
      "None needed. :has() is Baseline widely available, so this works everywhere.",
  },
  {
    featureId: "dialog",
    where: "The 'How this is measured' modal.",
    instead: "react-modal, or a hand-built focus trap.",
    fallback:
      "None needed. The top layer, backdrop, focus trap and Escape are all the element's own behaviour.",
    ruleId: "dialog-element",
  },
  {
    featureId: "invoker-commands",
    where: "Opening and closing that modal, with command and commandfor.",
    instead:
      "An onClick handler calling showModal(), which needs a client component.",
    fallback:
      "The button does nothing. The data dates and web-features version are printed in the page footer regardless, so nothing load-bearing is only in the modal.",
  },
  {
    featureId: "dialog-closedby",
    where: "closedby='any' on that modal, so clicking the backdrop closes it.",
    instead:
      "A click handler comparing event.target, which is what the dialog rule warns you still have to write.",
    fallback:
      "The backdrop does not dismiss. Escape and the Close button still do.",
    ruleId: "dialog-element",
  },
  {
    featureId: "popover",
    where: "The 'What do the tiers mean?' explainer.",
    instead: "@floating-ui/react.",
    fallback:
      "Anchor positioning is Chromium-only, so elsewhere the popover opens centred rather than tethered to its trigger. It still opens, dismisses and traps focus.",
    ruleId: "popover-anchor-positioning",
  },
  {
    featureId: "anchor-positioning",
    where: "Tethering that same popover to its button.",
    instead: "JavaScript measuring the trigger on every scroll and resize.",
    fallback: "The popover centres itself in the viewport.",
    ruleId: "popover-anchor-positioning",
  },
  {
    featureId: "container-queries",
    where: "Findings reflow on their own width, not the viewport's.",
    instead: "react-resize-detector and a ResizeObserver.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "container-queries",
  },
  {
    featureId: "scroll-snap",
    where: "The featured rules strip on the home page.",
    instead: "swiper or embla-carousel.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "scroll-buttons",
    where: "The arrows beside that strip, generated by the browser.",
    instead: "The library's arrow markup, plus its disabled-state logic.",
    fallback: "No arrows. Dragging, the scrollbar and the keyboard still work.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "scroll-markers",
    where: "The dots under that strip, generated by the browser.",
    instead: "The same carousel library, plus its dot markup and ARIA.",
    fallback:
      "A thin scrollbar instead of dots. The strip still snaps and still scrolls.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "color-mix",
    where: "Every derived shade: hover states, borders, selection.",
    instead: "polished or color2k.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "css-color-functions",
  },
  {
    featureId: "light-dark",
    where: "The whole palette follows your OS preference.",
    instead: "A theme provider and a class on <html>.",
    fallback:
      "An explicit dark palette behind @supports. The site stops following the OS and stays dark.",
  },
  {
    featureId: "text-wrap-balance",
    where: "Every heading.",
    instead: "react-wrap-balancer.",
    fallback: "Ordinary wrapping, which occasionally orphans a word.",
    ruleId: "text-wrap-balance",
  },
  {
    featureId: "interpolate-size",
    where: "The 'keep it if' disclosures animate open.",
    instead: "react-collapse, or measuring the panel and animating to pixels.",
    fallback: "The panel opens instantly, which is the normal behaviour.",
    ruleId: "height-auto-animation",
  },
  {
    featureId: "starting-style",
    where: "The modal and popover fade and lift in, and back out.",
    instead: "framer-motion, or keeping the element mounted to animate it out.",
    fallback: "They appear and disappear without a transition.",
    ruleId: "discrete-transitions",
  },
  {
    featureId: "scroll-driven-animations",
    where: "The reading progress bar on a rule page.",
    instead: "A scroll listener updating a width on every frame.",
    fallback: "No progress bar. Nothing else changes.",
    ruleId: "scroll-driven-animations",
  },
  {
    featureId: "text-box",
    where: "Headings sit flush against the space above them.",
    instead: "capsize, or hand-tuned negative margins.",
    fallback:
      "The font's built-in leading stays, so spacing is slightly looser.",
    ruleId: "text-box-trim",
  },
  {
    featureId: "scrollbar-gutter",
    where: "The page does not shift sideways when content gets tall.",
    instead: "Measuring the scrollbar and padding for it.",
    fallback: "A small horizontal shift when a scrollbar appears.",
    ruleId: "styled-scrollbars",
  },
];

export default function NativePage() {
  return (
    <div className="space-y-10">
      <header>
        <h1 className="mb-4 text-page-title">What this site uses</h1>
        <p className="max-w-[62ch] text-fg-muted text-lede">
          This site is built from the catalog it publishes. Every feature below
          is doing real work here, and every one that is not Baseline sits
          behind an @supports check with a stated fallback, which is what the
          rules themselves ask you to do.
        </p>
      </header>

      <section className="hairline pt-8">
        <h2 className="mb-2 text-section">The one it does not use</h2>
        <p className="max-w-[62ch] text-compact text-fg-muted">
          View transitions. Next.js drives navigation through its client router,
          so the cross-document version of the API never fires, and wiring up
          the same-document one would be a claim about this site that is not
          true yet. The <Link href="/rules/view-transitions">rule</Link> is in
          the catalog on its merits, not because this site ships it.
        </p>
      </section>

      <section className="hairline pt-8">
        <h2 className="mb-5 text-section">{USAGE.length} features in use</h2>
        <ul className="rule-list">
          {USAGE.map((usage) => (
            <UsageRow key={`${usage.featureId}-${usage.where}`} usage={usage} />
          ))}
        </ul>
      </section>
    </div>
  );
}

function UsageRow({ usage }: { usage: Usage }) {
  const feature = resolveFeature(usage.featureId);
  const rule =
    usage.ruleId === undefined ? undefined : rulesById.get(usage.ruleId);

  return (
    <li className="py-5">
      <div className="mb-2 flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1">
        <h3 className="font-mono text-subsection">{feature.name}</h3>
        <BaselineBadge status={feature.status} short={true} />
      </div>

      <dl className="max-w-[66ch] space-y-1.5 text-compact">
        <div className="flex flex-wrap gap-x-2">
          <dt className="shrink-0 text-fg-faint">Here</dt>
          <dd className="text-fg-muted">{usage.where}</dd>
        </div>
        <div className="flex flex-wrap gap-x-2">
          <dt className="shrink-0 text-fg-faint">Instead of</dt>
          <dd className="text-fg-muted">{usage.instead}</dd>
        </div>
        <div className="flex flex-wrap gap-x-2">
          <dt className="shrink-0 text-fg-faint">Without it</dt>
          <dd className="text-fg-muted">{usage.fallback}</dd>
        </div>
      </dl>

      {rule === undefined ? null : (
        <p className="mt-2.5 text-metadata">
          <Link href={`/rules/${rule.id}`}>{rule.title}</Link>
        </p>
      )}
    </li>
  );
}
