/**
 * What this site actually uses from its own catalog.
 *
 * A tool that tells you to drop libraries should be able to show its own work.
 * Each entry names a real feature used here, what it replaced, and what
 * happens in a browser that does not support it.
 *
 * This lives outside the page because two other things read it:
 * `scripts/refresh-baseline.ts` snapshots these feature IDs alongside the ones
 * the rules reference, and `scripts/check-freshness.ts` fails the build if any
 * of them is missing from that snapshot. Without that, a feature used only by
 * the site renders as "Unverified" with its raw ID.
 */

export interface Usage {
  featureId: string;
  where: string;
  instead: string;
  fallback: string;
  /** The catalog rule this exercises, when there is one. */
  ruleId?: string;
}

export const NATIVE_USAGE: readonly Usage[] = [
  {
    featureId: "field-sizing",
    where: "The paste box on the home page grows as you type.",
    instead: "react-textarea-autosize, or a hidden mirror element to measure.",
    fallback: "A fixed-height textarea that scrolls.",
    ruleId: "field-sizing",
  },
  {
    featureId: "has",
    where:
      "The tier filter on the catalog page, and the hint under the submit button.",
    instead: "Component state and a re-render on every change.",
    fallback:
      "None needed. :has() is Baseline widely available, so this works everywhere.",
  },
  {
    featureId: "dialog",
    where: "The 'How this is measured' modal.",
    instead: "react-modal, or a hand-built focus trap.",
    fallback:
      "None needed. The top layer, backdrop, focus trap and Escape are all the element's own behaviour.",
    ruleId: "dialog-element",
  },
  {
    featureId: "invoker-commands",
    where: "Opening and closing that modal, with command and commandfor.",
    instead:
      "An onClick handler calling showModal(), which needs a client component.",
    fallback:
      "The button does nothing. The data dates and web-features version are printed in the page footer regardless, so nothing load-bearing is only in the modal.",
  },
  {
    featureId: "dialog-closedby",
    where: "closedby='any' on that modal, so clicking the backdrop closes it.",
    instead:
      "A click handler comparing event.target, which is what the dialog rule warns you still have to write.",
    fallback:
      "The backdrop does not dismiss. Escape and the Close button still do.",
    ruleId: "dialog-element",
  },
  {
    featureId: "popover",
    where: "The 'What do the tiers mean?' explainer.",
    instead: "@floating-ui/react.",
    fallback:
      "Anchor positioning is Chromium-only, so elsewhere the popover opens centred rather than tethered to its trigger. It still opens, dismisses and traps focus.",
    ruleId: "popover-anchor-positioning",
  },
  {
    featureId: "anchor-positioning",
    where: "Tethering that same popover to its button.",
    instead: "JavaScript measuring the trigger on every scroll and resize.",
    fallback: "The popover centres itself in the viewport.",
    ruleId: "popover-anchor-positioning",
  },
  {
    featureId: "container-queries",
    where: "Findings reflow on their own width, not the viewport's.",
    instead: "react-resize-detector and a ResizeObserver.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "container-queries",
  },
  {
    featureId: "scroll-snap",
    where: "The featured rules strip on the home page.",
    instead: "swiper or embla-carousel.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "scroll-buttons",
    where: "The arrows beside that strip, generated by the browser.",
    instead: "The library's arrow markup, plus its disabled-state logic.",
    fallback: "No arrows. Dragging, the scrollbar and the keyboard still work.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "scroll-markers",
    where: "The dots under that strip, generated by the browser.",
    instead: "The same carousel library, plus its dot markup and ARIA.",
    fallback:
      "A thin scrollbar instead of dots. The strip still snaps and still scrolls.",
    ruleId: "carousel-scroll-markers",
  },
  {
    featureId: "color-mix",
    where: "Every derived shade: hover states, borders, selection.",
    instead: "polished or color2k.",
    fallback: "None needed. Baseline widely available.",
    ruleId: "css-color-functions",
  },
  {
    featureId: "light-dark",
    where: "The whole palette follows your OS preference.",
    instead: "A theme provider and a class on <html>.",
    fallback:
      "An explicit dark palette behind @supports. The site stops following the OS and stays dark.",
  },
  {
    featureId: "text-wrap-balance",
    where: "Every heading.",
    instead: "react-wrap-balancer.",
    fallback: "Ordinary wrapping, which occasionally orphans a word.",
    ruleId: "text-wrap-balance",
  },
  {
    featureId: "interpolate-size",
    where: "The 'keep it if' disclosures animate open.",
    instead: "react-collapse, or measuring the panel and animating to pixels.",
    fallback: "The panel opens instantly, which is the normal behaviour.",
    ruleId: "height-auto-animation",
  },
  {
    featureId: "starting-style",
    where: "The modal and popover fade and lift in, and back out.",
    instead: "framer-motion, or keeping the element mounted to animate it out.",
    fallback: "They appear and disappear without a transition.",
    ruleId: "discrete-transitions",
  },
  {
    featureId: "scroll-driven-animations",
    where: "The reading progress bar on a rule page.",
    instead: "A scroll listener updating a width on every frame.",
    fallback: "No progress bar. Nothing else changes.",
    ruleId: "scroll-driven-animations",
  },
  {
    featureId: "text-box",
    where: "Headings sit flush against the space above them.",
    instead: "capsize, or hand-tuned negative margins.",
    fallback:
      "The font's built-in leading stays, so spacing is slightly looser.",
    ruleId: "text-box-trim",
  },
  {
    featureId: "scrollbar-gutter",
    where: "The page does not shift sideways when content gets tall.",
    instead: "Measuring the scrollbar and padding for it.",
    fallback: "A small horizontal shift when a scrollbar appears.",
    ruleId: "styled-scrollbars",
  },
];

/** Every web-features ID the site depends on. */
export const NATIVE_FEATURE_IDS: readonly string[] = [
  ...new Set(NATIVE_USAGE.map((usage) => usage.featureId)),
];
