/**
 * Writes the catalog reference the agent skill loads on demand.
 *
 * The skill ships a full rule listing so an agent can answer "is this covered"
 * without spawning a process. A hand-written listing would drift the first
 * time someone adds a rule, so it is generated here and check-freshness fails
 * the build when it falls behind the catalog.
 *
 * Run: pnpm refresh:skill
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  baselineShortLabel,
  resolveBaseline,
} from "../packages/catalog/src/baseline.ts";
import { resolveGuides } from "../packages/catalog/src/guides.ts";
import { rules } from "../packages/catalog/src/rules/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "../skills/youmightnotneed/references/catalog.md");

const sorted = [...rules].sort((a, b) => a.title.localeCompare(b.title));

const rows = sorted.map((rule) => {
  const baseline = resolveBaseline(rule);
  const guides = resolveGuides(rule)
    .filter((guide) => guide.url !== null)
    .map((guide) => guide.id);
  return [
    `### ${rule.title}`,
    "",
    `- **id**: \`${rule.id}\``,
    `- **native**: ${rule.native}`,
    `- **support**: ${baselineShortLabel(baseline.status)}${
      baseline.limitedBy ? ` (capped by ${baseline.limitedBy.name})` : ""
    }`,
    `- **replaces**: ${rule.replaces.map((p) => `\`${p}\``).join(", ")}`,
    `- **when**: ${rule.agent.when}`,
    guides.length > 0 ? `- **guides**: ${guides.join(", ")}` : null,
  ]
    .filter((line) => line !== null)
    .join("\n");
});

const packageCount = new Set(rules.flatMap((rule) => rule.replaces)).size;

writeFileSync(
  outFile,
  `<!-- Generated by scripts/build-skill.ts. Do not edit by hand. -->
<!-- Run \`pnpm refresh:skill\` to update. -->

# The catalog

Every rule, ${rules.length} of them, covering ${packageCount} npm packages.
Sorted by title. Support is the Baseline tier of the least-supported feature
the replacement needs, so a rule reads as limited if any one part of it is.

To check a single package without reading this file:

\`\`\`sh
npx -y youmightnotneed@latest --package <name> --verbose
\`\`\`

The \`when\` line is the case the native approach covers. It is not the only
case the package is used for, which is why every rule also carries conditions
where the dependency is still right. Those are in the CLI's \`--verbose\`
output and in the MCP server's \`get_rule\`.

${rows.join("\n\n")}
`,
  "utf8",
);

console.info(
  `Wrote ${rules.length} rules to skills/youmightnotneed/references/catalog.md.`,
);
