/**
 * Writes the catalog reference the agent skill loads on demand.
 *
 * The skill ships a full rule listing so an agent can answer "is this covered"
 * without spawning a process. A hand-written listing would drift the first
 * time someone adds a rule, so it is generated here and check-freshness fails
 * the build when it falls behind the catalog.
 *
 * Run: pnpm refresh:skill
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  baselineShortLabel,
  resolveBaseline,
} from "../packages/catalog/src/baseline.ts";
import { resolveGuides } from "../packages/catalog/src/guides.ts";
import { rules } from "../packages/catalog/src/rules/index.ts";

const here = dirname(fileURLToPath(import.meta.url));
const outFile = join(here, "../skills/youmightnotneed/references/catalog.md");

const sorted = [...rules].sort((a, b) => a.title.localeCompare(b.title));

/**
 * The index that makes this file useful before a dependency exists. Keyed by
 * `agent.when`, which is the use case rather than the package name, so an
 * agent about to build a carousel can find the rule without knowing that
 * swiper is the package it was reaching for.
 */
const index = [...rules]
  .sort((a, b) => a.agent.when.localeCompare(b.agent.when))
  .map((rule) => {
    const status = baselineShortLabel(resolveBaseline(rule).status);
    return `| ${rule.agent.when} | ${rule.native} | ${status} | \`${rule.id}\` |`;
  });

const rows = sorted.map((rule) => {
  const baseline = resolveBaseline(rule);
  const guides = resolveGuides(rule)
    .filter((guide) => guide.url !== null)
    .map((guide) => guide.id);
  return [
    `### ${rule.title}`,
    "",
    `- **id**: \`${rule.id}\``,
    `- **native**: ${rule.native}`,
    `- **support**: ${baselineShortLabel(baseline.status)}${
      baseline.limitedBy ? ` (capped by ${baseline.limitedBy.name})` : ""
    }`,
    `- **replaces**: ${rule.replaces.map((p) => `\`${p}\``).join(", ")}`,
    `- **when**: ${rule.agent.when}`,
    guides.length > 0 ? `- **guides**: ${guides.join(", ")}` : null,
  ]
    .filter((line) => line !== null)
    .join("\n");
});

const packageCount = new Set(rules.flatMap((rule) => rule.replaces)).size;

writeFileSync(
  outFile,
  `<!-- Generated by scripts/build-skill.ts. Do not edit by hand. -->
<!-- Run \`pnpm refresh:skill\` to update. -->

# The catalog

Every rule, ${rules.length} of them, covering ${packageCount} npm packages.
Support is the Baseline tier of the least-supported feature the replacement
needs, so a rule reads as limited if any one part of it is.

To check a single package without reading this file:

\`\`\`sh
npx -y youmightnotneed@latest --package <name> --verbose
\`\`\`

## By use case

Read this before reaching for a package. The left column is the case the
native approach covers, so it is searchable without knowing which library you
were about to install.

| Building | The platform does | Support | Rule |
| --- | --- | --- | --- |
${index.join("\n")}

A match here is a starting point, not a verdict. Every rule also carries the
conditions where the dependency is still right, and those are not in this
file: run \`--package <name> --verbose\`, or call \`get_rule\` on the MCP
server, and read them before deciding.

## Every rule

Sorted by title.

${rows.join("\n\n")}
`,
  "utf8",
);

console.info(
  `Wrote ${rules.length} rules to skills/youmightnotneed/references/catalog.md.`,
);
