/**
 * Snapshots Baseline support for every web-features ID the catalog references.
 *
 * Baseline status is never written by hand. This script reads the
 * `web-features` package, the same data source behind Baseline itself, and
 * writes a small committed snapshot covering only the features the rules
 * actually use. The catalog then ships with no runtime dependency on
 * web-features, and the snapshot is reviewable in a diff when support moves.
 *
 * Run: pnpm refresh:baseline
 */
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { NATIVE_FEATURE_IDS } from "../apps/web/lib/native-usage.ts";
import { rules } from "../packages/catalog/src/rules/index.ts";

const require = createRequire(import.meta.url);
const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..");
const outFile = join(repoRoot, "packages/catalog/src/generated/baseline.ts");

interface WebFeature {
  name?: string;
  status?: {
    baseline?: "high" | "low" | false;
    baseline_low_date?: string;
    baseline_high_date?: string;
  };
  spec?: string | string[];
}

const { features } = require("web-features") as {
  features: Record<string, WebFeature>;
};
/** web-features does not export ./package.json, so read it off disk. */
function readWebFeaturesVersion(): string {
  let dir = dirname(require.resolve("web-features"));
  for (let depth = 0; depth < 5; depth += 1) {
    try {
      const pkg = JSON.parse(
        readFileSync(join(dir, "package.json"), "utf8"),
      ) as { name?: string; version?: string };
      if (pkg.name === "web-features" && pkg.version) return pkg.version;
    } catch {
      // Keep walking up.
    }
    dir = dirname(dir);
  }
  throw new Error("could not determine the installed web-features version");
}

const webFeaturesVersion = readWebFeaturesVersion();

/*
 * Rules are the main source, but the site also uses features no rule
 * references (:has(), invoker commands, light-dark()). Those need to be in the
 * snapshot too, or /native renders them as "Unverified" with a raw ID.
 */
const referenced = [
  ...new Set([
    ...rules.flatMap((rule) => rule.featureIds),
    ...NATIVE_FEATURE_IDS,
  ]),
].sort();

const missing = referenced.filter((id) => !features[id]);
if (missing.length > 0) {
  console.error(
    `These featureIds are not in web-features@${webFeaturesVersion}:\n  ${missing.join("\n  ")}\n\nFix the rule, or give it an explicit manualBaseline.`,
  );
  process.exit(1);
}

/** Dates arrive as YYYY-MM-DD, sometimes prefixed with a range marker. */
function cleanDate(value: string | undefined): string | null {
  if (!value) return null;
  const match = /\d{4}-\d{2}-\d{2}/.exec(value);
  return match ? match[0] : null;
}

function firstSpec(spec: string | string[] | undefined): string | null {
  if (!spec) return null;
  return Array.isArray(spec) ? (spec[0] ?? null) : spec;
}

const snapshot: Record<string, unknown> = {};
for (const id of referenced) {
  const feature = features[id];
  if (!feature) continue;
  snapshot[id] = {
    name: feature.name ?? id,
    baseline: feature.status?.baseline ?? false,
    lowDate: cleanDate(feature.status?.baseline_low_date),
    highDate: cleanDate(feature.status?.baseline_high_date),
    spec: firstSpec(feature.spec),
  };
}

const generatedOn = new Date().toISOString().slice(0, 10);

const body = `// Generated by scripts/refresh-baseline.ts. Do not edit by hand.
// Run \`pnpm refresh:baseline\` to update.

/** Raw Baseline state for one feature, as web-features reports it. */
export interface BaselineSnapshotEntry {
  /** Human-readable feature name, e.g. "Scroll snap". */
  name: string;
  /** "high" is widely available, "low" is newly available, false is limited. */
  baseline: "high" | "low" | false;
  /** Date the feature became newly available. */
  lowDate: string | null;
  /** Date the feature became widely available. */
  highDate: string | null;
  /** Canonical specification URL, when web-features records one. */
  spec: string | null;
}

export interface BaselineSnapshot {
  /** Date this snapshot was generated, YYYY-MM-DD. */
  generatedOn: string;
  /** The web-features release the data came from. */
  webFeaturesVersion: string;
  features: Record<string, BaselineSnapshotEntry>;
}

export const baselineSnapshot: BaselineSnapshot = ${JSON.stringify(
  { generatedOn, webFeaturesVersion, features: snapshot },
  null,
  2,
)};
`;

writeFileSync(outFile, body, "utf8");

const tally = { high: 0, low: 0, limited: 0 };
for (const entry of Object.values(snapshot) as { baseline: unknown }[]) {
  if (entry.baseline === "high") tally.high += 1;
  else if (entry.baseline === "low") tally.low += 1;
  else tally.limited += 1;
}

console.info(
  `Wrote ${referenced.length} features from web-features@${webFeaturesVersion} (${tally.high} widely, ${tally.low} newly, ${tally.limited} limited)`,
);
